version: '3.8'

services:
  app:
    image: nganle18/dockerdemo:0.0.1
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/productdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: anhdagia
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: anhdagia
      MYSQL_DATABASE: productdb

    networks:
      - app-network

networks:
  app-network:
